server:
  port: 8402

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iotdb
    username: iotuser
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

ai:
  server:
    url: http://localhost:8000