server:
  port: ${SERVER_PORT:8402}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/iat-ai-phm-postgres?currentSchema=iat_ai_safety}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:iat_ai_safety}
        hbm2ddl:
          create_namespaces: true
        format_sql: true
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8000}
app:
  demo:
    write-protection-enabled: ${DEMO_WRITE_PROTECTION_ENABLED:true}
    write-token: ${DEMO_WRITE_TOKEN:}
