server:
  port: 8402

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iat-ai-phm-postgres
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

ai:
  server:
    url: http://localhost:8000